Fix: Makefile: problem with empty DESTDIR
Leave DESTDIR_REALPATH variable empty if DESTDIR is not set.

executing `realpath $(DESTDIR)` on Ubuntu fails with:

  error: the following required arguments were not provided:
    <files>...

  Usage: realpath [OPTION]... FILE...

  For more information, try '--help'.

I do not know how the `realpath` works on another OSs,
but from the doc it seems to expect always 'filename' argument.

https://linux.die.net/man/1/realpath

This fix is only to make it work if the DESTDIR variable is not
passed or is empty. No other functional change.

Note: The DESTDIR_REALPATH variable was added by commit 341bd08.

Signed-off-by: Martin Flaska <mato.flaska@gmail.com>